// Builds the explorer into oto/ui/explorer/. One bundle, React and React Flow inside, no runtime
// network; the CSS of React Flow is inlined into explorer.css. Run from ui-src/: `npm run build`.
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "oto", "ui", "explorer");
mkdirSync(out, { recursive: true });

await build({
  entryPoints: [join(here, "explorer", "main.jsx")],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2019"],
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  outfile: join(out, "explorer.js"),
  legalComments: "none",
  logLevel: "info",
});

const rfCss = readFileSync(join(here, "node_modules", "@xyflow", "react", "dist", "style.css"), "utf8");
const ours = readFileSync(join(here, "explorer", "explorer.css"), "utf8");
writeFileSync(join(out, "explorer.css"), "/* React Flow base styles (MIT), then the explorer's own. Generated by ui-src/build.mjs. */\n" + rfCss + "\n" + ours);
console.log("wrote", join(out, "explorer.css"));
